
[[constraint]]
  name = "git.apache.org/thrift.git"
  version = "0.11.0"

[[constraint]]
  name = "github.com/Microsoft/go-winio"
  version = "0.4.9"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
