package: github.com/kolide/osquery-go
import:
- package: git.apache.org/thrift.git
  version: 0dd823580c78a79ae9696eb9b3650e400fff140f
  subpackages:
  - lib/go/thrift
- package: github.com/pkg/errors
  version: ^0.8.0
- package: github.com/stretchr/testify
  version: ^1.1.4
  subpackages:
  - assert
- package: github.com/Microsoft/go-winio
  version: ^0.4.5
