
[[constraint]]
  # This version includes concurrency fixes, but excludes changes to the
  # library APIs. Using a version beyond this would require users to build the
  # Thrift compiler from source to get API-compatible generated code. After the
  # next Thrift release, this should become that tagged release (and the code
  # generated appropriately).
  name = "git.apache.org/thrift.git"
  revision = "0dd823580c78a79ae9696eb9b3650e400fff140f"

[[constraint]]
  name = "github.com/Microsoft/go-winio"
  version = "0.4.5"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
