version: 2
jobs:
  build-go-latest:
    docker:
        - image: golang:1.10
    working_directory: /go/src/github.com/kolide/osquery-go
    steps: &steps
      - checkout

      - restore_cache:
          keys:
            - vendor-cache-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
            - vendor-cache-{{ .Branch }}
            - vendor-cache
      - run: make deps
      - save_cache:
          key: vendor-cache-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - save_cache:
          key: vendor-cache-{{ .Branch }}
          paths:
            - vendor
      - save_cache:
          key: vendor-cache
          paths:
            - vendor

      - run: go test -race -cover -v $(go list ./... | grep -v /vendor/)
      - run: make examples

  build-go1.9:
    docker:
        - image: golang:1.9
    working_directory: /go/src/github.com/kolide/osquery-go
    steps: *steps

workflows:
  version: 2
  build:
    jobs:
      - build-go-latest
      - build-go1.9

